### ISSUE TITLE
Database Recovery Pending

### ISSUE THREAD

**Issue by HeymansNickk** [HOGENT-Databases/DB2-Workshops#8]
![sql recovery pending](https://user-images.githubusercontent.com/36665292/74734812-a3124900-524f-11ea-9dd6-63c415cb5144.png)

**Comment by vertonghenb** [comment]
# Reasons Why:
- The database isn’t cleanly shut down, that is, there is at least one uncommitted transaction active at the time the database is shut down and the log file for it has been deleted
- User has tried to move the log files to a new drive to overcome server performance issues but in the process, ended up corrupting the log files
- Database Recovery cannot be initiated due to insufficient memory space or disk storage

# A possible solution
1. Make sure the database is not located on an external hard drive.
2. Drop the database, recreate the database
   > This can be harmful in Production, but as exercise it won't be an issue at this point in time.
